### ISSUE TITLE
Log file [x of y] incorrect

### ISSUE THREAD

**Issue by jamieburchell** [s3tools/s3cmd#421]
Excerpt from a log file from s3cmd 1.5.0-beta1. It shows that there's an error with the [x of y] numbering at the end of file operations.

```
INFO: Applying --exclude/--include
INFO: Applying --exclude/--include
INFO: Verifying attributes...
INFO: Summary: 12 local files to upload, 0 files to remote copy, 2 remote files to delete
WARNING: Retrying failed request: /Audio/Various%20Artists/The%20Age%20of%20Outsiders,%20Volume%202/07%20Macc%20%26%20John%20Atterbury%20-%20Seeds.mp3 ('')
WARNING: Waiting 3 sec...
deleted: 's3://xxx/Audio/Various Artists/The Age of Outsiders, Volume 2/07 Macc & John Atterbury - Seeds.mp3'
deleted: 's3://xxx/Audio/Various Artists/The Age of Outsiders, Volume 2/08 DJ Trax feat Funkshone - Resistance is Futile.mp3'
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
INFO: Sending file '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/07 Macc + John Atterbury - Seeds.mp3', please wait...
File '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/07 Macc + John Atterbury - Seeds.mp3' stored as 's3://xxx/Audio/Various Artists/The Age of Outsiders, Volume 2/07 Macc + John Atterbury - Seeds.mp3' (10926828 bytes in 47.2 seconds, 225.87 kB/s) [1 of 2]
INFO: Sending file '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/08 DJ Trax feat. Funkshone - Resistance is Futile.mp3', please wait...
File '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/08 DJ Trax feat. Funkshone - Resistance is Futile.mp3' stored as 's3://xxx/Audio/Various Artists/The Age of Outsiders, Volume 2/08 DJ Trax feat. Funkshone - Resistance is Futile.mp3' (13397749 bytes in 57.9 seconds, 226.00 kB/s) [2 of 2]
INFO: Sending file '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/01 Infest - The Day in Pictures.mp3', please wait...
File '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/01 Infest - The Day in Pictures.mp3' stored as 's3://xxx/Audio/Various Artists/The Age of Outsiders, Volume 2/01 Infest - The Day in Pictures.mp3' (15131864 bytes in 65.2 seconds, 226.78 kB/s) [3 of 2]
INFO: Sending file '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/02 ASC - Stardust.mp3', please wait...
INFO: Sending file '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/02 ASC - Stardust.mp3', please wait...
File '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/02 ASC - Stardust.mp3' stored as 's3://xxx/Audio/Various Artists/The Age of Outsiders, Volume 2/02 ASC - Stardust.mp3' (16784969 bytes in 72.9 seconds, 224.98 kB/s) [4 of 2]
INFO: Sending file '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/03 Spotless - Mano Liudesys.mp3', please wait...
File '/share/Multimedia/Audio/Various Artists/The Age of Outsiders, Volume 2/03 Spotless - Mano Liudesys.mp3' stored as 's3://xxx/Audio/Various Artists/The Age of Outsiders, Volume 2/03 Spotless - Mano Liudesys.mp3' (13996635 bytes in 60.4 seconds, 226.41 kB/s) [5 of 2]
```

**Comment by mdomsch** [comment]
Please try with 1.5.0 release or upstream master. I believe this was fixed before 1.5.0 was released.

**Comment by jamieburchell** [comment]
This bug still seems to be present on 1.5.2:

E.g.:

```
Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe' (143783408 bytes in 902.6 seconds, 155.56 kB/s) [4 of 2]
```

Full log:

```
INFO: Compiling list of local files...
INFO: Running stat() and reading/calculating MD5 values on 406 files, this may take some time...
INFO: Retrieving list of remote files for s3://peanet/Applications/ ...
INFO: Found 406 local files, 403 remote files
INFO: Verifying attributes...
INFO: Summary: 3 local files to upload, 2 files to remote copy, 2 remote files to delete
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe', please wait...
File '/share/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe' stored as 's3://peanet/Applications/PowerDVD/CyberLink_PowerDVD14_Pro_DVD140826-02.exe' (148192560 bytes in 802.3 seconds, 180.38 kB/s) [1 of 3]
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
INFO: Sending file '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe', please wait...
File '/share/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe' stored as 's3://peanet/Applications/PowerDVD/PowerDVD_14.0.4704.58_Patch_DVD140911-04.exe' (148100944 bytes in 781.6 seconds, 185.04 kB/s) [2 of 3]
INFO: Sending file '/share/Applications/PowerDVD/key.txt', please wait...
File '/share/Applications/PowerDVD/key.txt' stored as 's3://peanet/Applications/PowerDVD/key.txt' (35 bytes in 0.2 seconds, 223.45 B/s) [3 of 3]
ERROR: S3 error: Operation is not valid for the source object's storage class
WARNING: Unable to remote copy files s3://peanet/Applications/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe -> s3://peanet/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe
ERROR: S3 error: Operation is not valid for the source object's storage class
WARNING: Unable to remote copy files s3://peanet/Applications/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe -> s3://peanet/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
WARNING: Upload failed: /Applications/@Recycle/PowerDVD%2010%20Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe?partNumber=8&uploadId=Ice90sWx6lVyQeTvvfTQkfJt_CMW9H8OQ6G5.WhDFP81QHodhjQAXHEzYG_4GUUJ0bfMdXVHb1l7YFSkIH0SAK9phLKxoLUO6MsUKmrpyTajj8M5zXboeEL7gLssDjdJ ([Errno 104] Connection reset by peer)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe', please wait...
File '/share/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe' stored as 's3://peanet/Applications/@Recycle/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe' (143783408 bytes in 902.6 seconds, 155.56 kB/s) [4 of 2]
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
INFO: Sending file '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe', please wait...
File '/share/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe' stored as 's3://peanet/Applications/@Recycle/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe' (119733672 bytes in 658.7 seconds, 177.52 kB/s) [5 of 2]
File s3://peanet/Applications/PowerDVD 10 Upgrade/PowerDVD_v5202_RiTA10(Patch)_Patch_DVD130415-01.exe deleted
File s3://peanet/Applications/PowerDVD 10 Upgrade/TSST.v4126_RiTA10(AW_DVD121025-01.exe deleted
Done. Uploaded 559810619 bytes in 3146.2 seconds, 173.76 kB/s. Copied 2 files saving 0 bytes transfer.
```

Possibly this happens when a multi-part file fails to download?

Cheers
Jamie
