### ISSUE TITLE
Encoding exception when using python-magic

### ISSUE THREAD

**Issue by fviard** [s3tools/s3cmd#528]
Matt Makulski's message:
Hi,

Please see the report below:

Invoked as: /opt/backups/s3cmd/s3cmd --delete-removed --delete-after --exclude dev/* --exclude temp/* --exclude sessions/* -q sync /opt/vhosts/xxx.com/ s3://backups/xxx.com/
Problem: ArgumentError: argument 2: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xf3' in position 48: ordinal not in range(128)
S3cmd:   1.5.2
python:   2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2]
environment LANG=en_IE.UTF-8

Traceback (most recent call last):
 File "/opt/backups/s3cmd/s3cmd", line 2579, in <module>
   rc = main()
 File "/opt/backups/s3cmd/s3cmd", line 2491, in main
   rc = cmd_func(args)
 File "/opt/backups/s3cmd/s3cmd", line 1490, in cmd_sync
   return cmd_sync_local2remote(args)
 File "/opt/backups/s3cmd/s3cmd", line 1467, in cmd_sync_local2remote
   any_child_failed = _single_process(local_list)
 File "/opt/backups/s3cmd/s3cmd", line 1272, in _single_process
   rc = _child(destination_base, local_list)
 File "/opt/backups/s3cmd/s3cmd", line 1408, in _child
   n, total_size = _upload(local_list, 0, upload_count, total_size)
 File "/opt/backups/s3cmd/s3cmd", line 1332, in _upload
   response = s3.object_put(src, uri, extra_headers, extra_label = seq_label)
 File "/opt/backups/s3cmd-master/S3/S3.py", line 551, in object_put
   headers["content-type"] = self.content_type(filename=filename)
 File "/opt/backups/s3cmd-master/S3/S3.py", line 499, in content_type
   (content_type, content_charset) = self._guess_content_type(filename)
 File "/opt/backups/s3cmd-master/S3/S3.py", line 476, in _guess_content_type
   (content_type, content_charset) = mime_magic(filename)
 File "/opt/backups/s3cmd-master/S3/S3.py", line 90, in mime_magic
   result = _mime_magic(file)
 File "/opt/backups/s3cmd-master/S3/S3.py", line 85, in _mime_magic
   magictype = mime_magic_file(file)
 File "/opt/backups/s3cmd-master/S3/S3.py", line 56, in mime_magic_file
   return magic_.file(file)
 File "/usr/lib/python2.7/dist-packages/magic.py", line 122, in file
   return _file(self._magic_t, filename)
ArgumentError: argument 2: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\xf3' in position 48: ordinal not in range(128)

**Comment by enoadmin** [comment]
I can confirm that the changes from c07238c fixed the issue from the original report. Thank you Florent! Matt

**Comment by karlvr** [comment]
I am still having an issue after using the patch above. I'm running master (as of right now) + that patch. Here is the error I'm getting below. It appears that it's correctly catching the first failure, but still failing the second time when it calls `magictype = mime_magic_file(unicodise(file))`.

```
Problem: ArgumentError: argument 2: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\uf029' in position 17: ordinal not in range(128)
S3cmd:   1.5.2
python:   2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
environment LANG=en_NZ.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2586, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2498, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1496, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/bin/s3cmd", line 1473, in cmd_sync_local2remote
    any_child_failed = _single_process(local_list)
  File "/usr/bin/s3cmd", line 1278, in _single_process
    rc = _child(destination_base, local_list)
  File "/usr/bin/s3cmd", line 1414, in _child
    n, total_size = _upload(local_list, 0, upload_count, total_size)
  File "/usr/bin/s3cmd", line 1338, in _upload
    response = s3.object_put(src, uri, extra_headers, extra_label = seq_label)
  File "/usr/share/s3cmd/S3/S3.py", line 552, in object_put
    headers["content-type"] = self.content_type(filename=filename)
  File "/usr/share/s3cmd/S3/S3.py", line 500, in content_type
    (content_type, content_charset) = self._guess_content_type(filename)
  File "/usr/share/s3cmd/S3/S3.py", line 477, in _guess_content_type
    (content_type, content_charset) = mime_magic(filename)
  File "/usr/share/s3cmd/S3/S3.py", line 91, in mime_magic
    result = _mime_magic(file)
  File "/usr/share/s3cmd/S3/S3.py", line 88, in _mime_magic
    magictype = mime_magic_file(unicodise(file))
  File "/usr/share/s3cmd/S3/S3.py", line 57, in mime_magic_file
    return magic_.file(file)
  File "/usr/lib/python2.7/dist-packages/magic.py", line 122, in file
    return _file(self._magic_t, filename)
ArgumentError: argument 2: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\uf029' in position 17: ordinal not in range(128)
```

**Comment by karlvr** [comment]
So I've fixed it, just by ignoring the next exception and just going with `None` as the magictype. @fviard what do you think? Would you like to roll that into your patch? I'm not really a Python programmer so I put in that redundant `magictype = None` line because I wasn't sure what else to put there :-) I guess just nothing?

```
   def _mime_magic(file):
        magictype = None
        try:
            magictype = mime_magic_file(file)
        except (UnicodeDecodeError, UnicodeEncodeError, ArgumentError):
            try:
                magictype = mime_magic_file(unicodise(file))
            except (UnicodeDecodeError, UnicodeEncodeError, ArgumentError):
                magictype = None
        return magictype
```

**Comment by fviard** [comment]
Hi @karlvr,
I'm sorry to have not replied to you earlier but really thank you very much for your report of still having an issue. Because of that, I was able to notice that my previous fix was only a dirty partial fix and that indeed, a bigger change of the code should have be done to fix the issue.
Now, that should be resolved with the following pull request:
https://github.com/s3tools/s3cmd/pull/572
Could it be possible for you to give it a try?

@enoadmin: Is it possible for you to also give a try to this new patch?

(I did try with file-5.11, the same that should have karlvr but not with the other libs)
Thank you very much

**Comment by enoadmin** [comment]
Hi Florent,

I tried and the error has been gone since, thank you!


Best regards,

Matt

On 18 Jun 2015, at 08:28, Florent Viard <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @karlvr<https://github.com/karlvr>,
I'm sorry to have not replied to you earlier but really thank you very much for your report of still having an issue. Because of that, I was able to notice that my previous fix was only a dirty partial fix and that indeed, a bigger change of the code should have be done to fix the issue.
Now, that should be resolved with the following pull request:
#572<https://github.com/s3tools/s3cmd/pull/572>
Could it be possible for you to give it a try?

@enoadmin<https://github.com/enoadmin>: Is it possible for you to also give a try to this new patch?

(I did try with file-5.11, the same that should have karlvr but not with the other libs)
Thank you very much

**Comment by karlvr** [comment]
@fviard Thanks for the follow up. I've grabbed your build and I'm running a test now. It runs for several hours before it usually fails. I'll report back.

I have been trouble free with my previous solution (as above), so it will be interesting to see if this results in any missed or different file names being uploaded.

Best,
Karl

**Comment by karlvr** [comment]
@fviard Confirmed I haven't got any issues. I am now reverting back to the 1.5.2 release version to confirm that the error still exists in my current setup.

**Comment by karlvr** [comment]
@fviard Hmm, well 1.5.2 isn't erroring for me anymore... I guess those files moved on. So I unfortunately can't confirm the fix, but I will continue to use your version!
