### ISSUE TITLE
s3cmd sync s3 -> network share fails : 'ascii' codec can't decode byte 0xcc in position 21: ordinal not in range(128)

### ISSUE THREAD

**Issue by ramonsmits** [s3tools/s3cmd#642]
Getting the following error:

OS: OS X 10.10.5

```
Invoked as: /usr/local/Cellar/s3cmd/1.5.0/libexec/bin/s3cmd sync --verbose --cache-file s3cmd-md5-cache.txt --exclude @eaDir/* --exclude .DS_Store/* s3://[bucketname]/diskstation/photo/s3/ /Volumes/photo/s3/
Traceback (most recent call last):
  File "/usr/local/Cellar/s3cmd/1.5.0/libexec/bin/s3cmd", line 2604, in <module>
    report_exception(e)
  File "/usr/local/Cellar/s3cmd/1.5.0/libexec/bin/s3cmd", line 2486, in report_exception
    sys.stderr.write(u"Problem: %s: %s\n" % (e_class, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 21: ordinal not in range(128)
```

**Comment by mdomsch** [comment]
You hit a unicode exception while trying to report another exception.
Boom.  A bunch of these have been fixed in 1.6.0.

**Comment by fviard** [comment]
Should already be fixed with latest master.

**Comment by santillaner** [comment]
It still fails for me in version 2.0.0. Already wrote to s3tools-bugs@lists.sourceforge.net

s3cmd> 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


s3cmd> Invoked as: /usr/local/Cellar/s3cmd/2.0.0/libexec/bin/s3cmd --config /Users/myuser/dev/tramitapp/hr-webapp/scheduler/job_fns/.s3cfg --no-preserve --delete-removed sync s3://MY_BUCKET_NAME/docs/ /tmp/myfolder/docs/

s3cmd> Traceback (most recent call last):
  File "/usr/local/Cellar/s3cmd/2.0.0/libexec/bin/s3cmd", line 3076, in <module>

s3cmd>     report_exception(e)

s3cmd>   File "/usr/local/Cellar/s3cmd/2.0.0/libexec/bin/s3cmd", line 2947, in report_exception

s3cmd>     sys.stderr.write(u"Problem: %s: %s\n" % (e_class, e))

s3cmd> UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 95: ordinal not in range(128)
