### ISSUE TITLE
gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by fabiodomingues** [s3tools/s3cmd#683]
I'm trying to use s3cmd on Ubuntu to sync a S3 Bucket to local.
I installed the latest version v1.6.0 and then I configured everything.

Then I ran: <code>s3cmd sync s3://mybucket/ --delete-removed /myfolder</code> and after synchronizing some files I get this error:

<code>
Problem: gaierror: [Errno -2] Name or service not known
S3cmd:   1.6.0
python:   2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2805, in <module>
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2713, in main
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1668, in cmd_sync
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1310, in cmd_sync_remote2local
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.0-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1151, in _download
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 637, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 1327, in recv_file
    conn.c.endheaders()
  File "/usr/lib/python2.7/httplib.py", line 975, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 835, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 797, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1178, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
</code>

Can someone help me?

PS: my bucket has about 70GB of files.

Regards
Fabio.

**Comment by fabiodomingues** [comment]
With debug on i get this information:

<code>
DEBUG: get_hostname(mybucket): mybucket.s3.amazonaws.com
DEBUG: ConnMan.get(): re-using connection: https://mybucket.s3.amazonaws.com#500
DEBUG: format_uri(): /Empresa_1/0_anexos/anexo_122928.pdf
 0 of 0     0% in    0s     0.00 B/s  failed
</code>

After call format_uri() received the failed message.

**Comment by mdomsch** [comment]
Can you git checkout 0a76134.  And report success/fail thereafter please? I
am curious if something broke last week here.
Thanks.

**Comment by fabiodomingues** [comment]
Starts synchronization, some files are synchronized and after a while and get this error.

**Comment by danhstevens** [comment]
I'm seeing the same/similar error:

```
s3cmd -dv ls
WARNING: Retrying failed request: / ([Errno -2] Name or service not known)
WARNING: Waiting 3 sec...
```

**Comment by vlkv** [comment]
Same problem

**Comment by dingxing123** [comment]
I got the same error, but at last , i  resvoled it. Follow the steps below:
1.check your config
    Use HTTPS protocol: False
    HTTP Proxy server name: (must blank)
    HTTP Proxy server port: 0
2, if HTTP Proxy server name not blank, edit config file.
    $ vi /root/.s3cfg
    proxy_host = 
    proxy_port = 0

**Comment by theemstra** [comment]
>> Use HTTPS protocol: False

Same error as @vlkv.
Disabling HTTPS makes s3cmd work again, but create security concerns

**Comment by fviard** [comment]
@theemstra Are you still encountering this issue with the latest master? Could you post your config exception the secret/access keys?

**Comment by fviard** [comment]
Should be fixed now? otherwise please reopen.

**Comment by lmolla** [comment]
> @theemstra Are you still encountering this issue with the latest master? Could you post your config exception the secret/access keys?

I am still having the same issue. what is the solution to this
