### ISSUE TITLE
CertificateError on RHEL7

### ISSUE THREAD

**Issue by mariebo** [s3tools/s3cmd#769]
If I try to list all buckets; everything is ok (`s3cmd ls s3://`)

but when I try to list contents of an example-bucket (`s3cmd ls s3://example-bucket` or `s3cmd --no-check-certificate ls s3://example-bucket`), s3cmd throws error with this message:

```
File "$TEST_PATH/S3/S3.py", line 1111, in send_request
    conn.counter = ConnMan.conn_max_counter
UnboundLocalError: local variable 'conn' referenced before assignment
```

Line 1093 in file S3.py throws an exception and variable `conn` is not initialised. Then in the except block script tries to access `conn`, so it throws an exception again, which shadows the other one.
So I added a line before 1111 line in S3.py, which contains `raise` and I received a different result with `s3cmd ls s3://example-bucket` command:
`CertificateError: hostname 'test-bucket.my-host-base' doesn't match 'my-host-base'`

I work on code from master branch.

What could be the problem?

My configuration:
Python 2.7.5
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2

**Comment by fviard** [comment]
Hi @mariebo 
Everything related to certificates should now be fixed in master and the "UnboundLocalError" should not be hiding real issues anymore.
Is it possible for you to test the last master to tell me if you are still encountering an issue?

Thank you

**Comment by mariebo** [comment]
I tested the last master. "UnboundLocalError" doesn't appear, but "CertificateError", which I mentioned above still appears. I tested aws-cli tool and it works properly with `--endpoint-url` option, but I'd like to use s3cmd.

**Comment by timss** [comment]
@mariebo Please see the comments in #772

**Comment by fviard** [comment]
@mariebo, Can you try again with the last master please? That should really
be fixed now.

**Comment by mariebo** [comment]
Thanks @fviard for your response. I really tried the last master, but "CertificateError" still appears. I read comments @timss  but my hostname isn't configured as "host:port".

**Comment by fviard** [comment]
@mariebo This is strange. Would you mind to post us your configuration? the host-base and host-bucket and the exact error message?
You can scramble it by changing letters, but please preserve all special characters, dot, minus, etc...

**Comment by mariebo** [comment]
@fviard Thanks for your response. My configuration:
`host_base = d1-dummy-1.dummmy.dum-dum.net
host_bucket = %(bucket)s.d1-dummy-1.dummmy.dum-dum.net`

And error with `--debug` flag:

```
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'ls' using UTF-8
DEBUG: Unicodising 's3://test-bucket' using UTF-8
DEBUG: Command: ls
DEBUG: Bucket 's3://test-bucket':
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Tue, 30 Aug 2016 12:35:52 +0000\n/test-bucket/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(test-bucket): test-bucket.d1-dummy-1.dummmy.dum-dum.net
DEBUG: ConnMan.get(): creating new connection: proxy://10.10.10.10:8080
DEBUG: Using ca_certs_file None
DEBUG: httplib.HTTPSConnection() has both context and check_hostname
DEBUG: proxied HTTPSConnection(10.10.10.10, 8080)
DEBUG: tunnel to test-bucket.d1-dummy-1.dummmy.dum-dum.net, None

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /$TEST_PATH/s3cmd/s3cmd ls s3://test-bucket
Problem: CertificateError: hostname 'test-bucket.d1-dummy-1.dummmy.dum-dum.net' doesn't match 'd1-dummy-1.dummmy.dum-dum.net'
S3cmd:   1.6.1
python:   2.7.5 (default, Oct 11 2015, 17:47:16)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/$TEST_PATH/s3cmd/s3cmd", line 2929, in <module>
    rc = main()
  File "/$TEST_PATH/s3cmd/s3cmd", line 2851, in main
    rc = cmd_func(args)
  File "/$TEST_PATH/s3cmd/s3cmd", line 120, in cmd_ls
    subcmd_bucket_list(s3, uri)
  File "/$TEST_PATH/s3cmd/s3cmd", line 153, in subcmd_bucket_list
    response = s3.bucket_list(bucket, prefix = prefix)
  File "/$TEST_PATH/s3cmd/S3/S3.py", line 298, in bucket_list
    for dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params):
  File "/$TEST_PATH/s3cmd/S3/S3.py", line 325, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params)
  File "/$TEST_PATH/s3cmd/S3/S3.py", line 344, in bucket_list_noparse
    response = self.send_request(request)
  File "/$TEST_PATH/s3cmd/S3/S3.py", line 1093, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/$TEST_PATH/s3cmd/S3/ConnMan.py", line 210, in get
    conn.c.connect()
  File "/usr/lib64/python2.7/httplib.py", line 1198, in connect
    server_hostname=sni_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib64/python2.7/ssl.py", line 588, in __init__
    self.do_handshake()
  File "/usr/lib64/python2.7/ssl.py", line 818, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib64/python2.7/ssl.py", line 273, in match_hostname
    % (hostname, dnsnames[0]))
CertificateError: hostname 'test-bucket.d1-dummy-1.dummmy.dum-dum.net' doesn't match 'd1-dummy-1.dummmy.dum-dum.net'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by timss** [comment]
Does the certificate issued actually match `*.d1-dummy-1.dummmy.dum-dum.net` (wildcard SSL certificate)?

**Comment by fviard** [comment]
Good question in fact.
(Note: @mariebo, if you need to bypass this issue for short term, or that you don't have a "wildcard" hostname in your certificate, you still can use the "--no-check-hostname" switch that will disable the ssl check for valid hostname)

**Comment by mariebo** [comment]
Certificate doesn't match wildcard SSL certificate, but on RHEL 4 (with s3cmd 1.5.1.2 and Python 2.6.6) it didn't make any problems. @fviard s3cmd with `--no-check-hostname` flag still causes error which I mentioned above (with additional line: `DEBUG: Disabling SSL certificate hostname checking`).

**Comment by Apexcarver** [comment]
I am also seeing a certificate error.

[jeff@CentOS ~]$ s3cmd -d --ca-certs=./server.pem ls
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/home/jeff/.s3cfg'
DEBUG: ConfigParser: access_key->jp...3_chars...6
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->US
DEBUG: ConfigParser: ca_certs_file->
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: check_ssl_certificate->False
DEBUG: ConfigParser: check_ssl_hostname->False
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: expiry_date->
DEBUG: ConfigParser: expiry_days->
DEBUG: ConfigParser: expiry_prefix->
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3p002.hgst-esp.com
DEBUG: ConfigParser: host_bucket->
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: kms_key->
DEBUG: ConfigParser: limitrate->0
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: long_listing->False
DEBUG: ConfigParser: max_delete->-1
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->443
DEBUG: ConfigParser: put_continue->False
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->65536
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: requester_pays->False
DEBUG: ConfigParser: restore_days->1
DEBUG: ConfigParser: secret_key->s3...6_chars...6
DEBUG: ConfigParser: send_chunk->65536
DEBUG: ConfigParser: server_side_encryption->False
DEBUG: ConfigParser: signature_v2->True
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: stop_on_error->False
DEBUG: ConfigParser: storage_class->
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: use_mime_magic->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config ca_certs_file -> ./server.pem
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'ls' using UTF-8
DEBUG: Command: ls
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Tue, 15 Nov 2016 18:19:12 +0000\n/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(None): s3p002.hgst-esp.com
DEBUG: ConnMan.get(): creating new connection: https://s3p002.hgst-esp.com
DEBUG: Using ca_certs_file ./server.pem
DEBUG: Disabling SSL certificate checking

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising '/usr/bin/s3cmd' using UTF-8
DEBUG: Unicodising '-d' using UTF-8
DEBUG: Unicodising '--ca-certs=./server.pem' using UTF-8
DEBUG: Unicodising 'ls' using UTF-8
Invoked as: /usr/bin/s3cmd -d --ca-certs=./server.pem ls
Problem: ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED
S3cmd:   1.6.1
python:   2.7.5 (default, Sep 15 2016, 22:37:39)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2954, in <module>
  File "/usr/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2876, in main
  File "/usr/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 127, in cmd_ls
  File "/usr/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 132, in subcmd_all_buckets_list
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 310, in list_all_buckets
    response = self.send_request(request)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 1151, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "build/bdist.linux-x86_64/egg/S3/ConnMan.py", line 231, in get
    conn = http_connection(conn_id, hostname, ssl, cfg)
  File "build/bdist.linux-x86_64/egg/S3/ConnMan.py", line 186, in __init__
    self.c = http_connection._https_connection(hostname)
  File "build/bdist.linux-x86_64/egg/S3/ConnMan.py", line 143, in _https_connection
    conn = httplib.HTTPSConnection(hostname, port, context=context, check_hostname=check_hostname)
  File "/usr/lib64/python2.7/httplib.py", line 1217, in __init__
    raise ValueError("check_hostname needs a SSL context with "
ValueError: check_hostname needs a SSL context with either CERT_OPTIONAL or CERT_REQUIRED

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
After a lot of investigation, I think that there is something strange with python versions that are in RHEL/Centos.

@Apexcarver : I have pushed to master a fix that I hope should fix your issue. Is it possible for you to try it?

@mariebo  : I just realized something from your previous comment. If it was working with RHEL 4 with python 2.6.6 it is because the real check of "valid certificate" and "hostnames" was only added to python in official version 2.7.9. But it looks like that red hat put some parts of the patch associated with this in earliest versions like 2.7.5 in the case of apexcarver. That looks very strange, is it also possible for your to try? I hope that at least my last patch with fix the situation for no check certifcate case.

**Comment by Apexcarver** [comment]
@fviard : Yes, I can run a test against it.  I will pull the master and take a look.

**Comment by Apexcarver** [comment]
@fviard : Success.  Here are some basic command minus debug and then a run with debug showing the parameters.

[jdempsey@centos ~]$ s3cmd ls
2016-10-27 17:24  s3://176
2016-10-27 18:13  s3://176-encrypt
2016-11-09 23:22  s3://testbucket
[jdempsey@centos ~]$ s3cmd la
2016-11-03 03:52       675   s3://176/.profile
2016-11-09 19:51     98881   s3://176/rel_notes.pdf

                       DIR   s3://176-encrypt/sanadm01/
2016-11-29 16:20 2506096640   s3://176-encrypt/centos6.6-solr4.10.3.qcow2
2016-11-02 22:32       185   s3://176-encrypt/foo
2016-11-29 21:01       711   s3://176-encrypt/issue
2016-11-09 19:46     98881   s3://176-encrypt/rel_notes.pdf


[jdempsey@centos ~]$ s3cmd du
99556    2 objects s3://176/
3774809537 5 objects s3://176-encrypt/
0        0 objects s3://testbucket/
--------
3774909093 Total
[jdempsey@centos ~]$ s3cmd -d la
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/home/jdempsey/.s3cfg'
DEBUG: ConfigParser: access_key->jp...3_chars...6
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->US
DEBUG: ConfigParser: ca_certs_file->/home/jdempsey/server.pem
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: check_ssl_certificate->False
DEBUG: ConfigParser: check_ssl_hostname->False
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: expiry_date->
DEBUG: ConfigParser: expiry_days->
DEBUG: ConfigParser: expiry_prefix->
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3..................com
DEBUG: ConfigParser: host_bucket->
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: kms_key->
DEBUG: ConfigParser: limitrate->0
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: long_listing->False
DEBUG: ConfigParser: max_delete->-1
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->443
DEBUG: ConfigParser: put_continue->False
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->65536
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: requester_pays->False
DEBUG: ConfigParser: restore_days->1
DEBUG: ConfigParser: secret_key->s3...6_chars...6
DEBUG: ConfigParser: send_chunk->65536
DEBUG: ConfigParser: server_side_encryption->False
DEBUG: ConfigParser: signature_v2->True
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: stop_on_error->False
DEBUG: ConfigParser: storage_class->
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: use_mime_magic->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'la' using UTF-8
DEBUG: Command: la
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Thu, 08 Dec 2016 00:14:02 +0000\n/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(None): s3p002.hgst-esp.com
DEBUG: ConnMan.get(): creating new connection: https://s3p002.hgst-esp.com
DEBUG: Using ca_certs_file /home/jdempsey/server.pem
DEBUG: Disabling SSL certificate checking
DEBUG: httplib.HTTPSConnection() has both context and check_hostname
DEBUG: non-proxied HTTPSConnection(s3p002.hgst-esp.com, None)
DEBUG: format_uri(): /
DEBUG: Sending request method_string='GET', uri='/', headers={'Authorization': 'AWS jpl176:P4nsHoDXEAXhMsGURoO0MRGTbEU=', 'x-amz-date': 'Thu, 08 Dec 2016 00:14:02 +0000'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (https://s3p002.hgst-esp.com#1)
DEBUG: Response:
{'data': '<?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>10680</ID><DisplayName>jpl176</DisplayName></Owner><Buckets><Bucket><Name>176</Name><CreationDate>2016-10-27T17:24:45.000Z</CreationDate></Bucket><Bucket><Name>176-encrypt</Name><CreationDate>2016-10-27T18:13:38.000Z</CreationDate></Bucket><Bucket><Name>testbucket</Name><CreationDate>2016-11-09T23:22:21.000Z</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>',
 'headers': {'accept-ranges': 'bytes',
             'content-length': '489',
             'content-type': 'application/xml',
             'date': 'Thu, 08 Dec 2016 00:13:00 GMT',
             'server': 'HGST-HGST Object Storage/3.9.0-6a0e66f36ebe'},
 'reason': 'OK',
 'status': 200}
DEBUG: Bucket 's3://176':
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Thu, 08 Dec 2016 00:14:02 +0000\n/176/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(176): s3p002.hgst-esp.com
DEBUG: ConnMan.get(): re-using connection: https://s3p002.hgst-esp.com#1
DEBUG: format_uri(): /176/?delimiter=/
DEBUG: Sending request method_string='GET', uri='/176/?delimiter=/', headers={'Authorization': 'AWS jpl176:S/JiSiuak70P4o1PB+INYzpg8WI=', 'x-amz-date': 'Thu, 08 Dec 2016 00:14:02 +0000'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (https://s3p002.hgst-esp.com#2)
DEBUG: Response:
{'data': '<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>176</Name><Prefix></Prefix><Marker/><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>.profile</Key><LastModified>2016-11-03T03:52:14.000Z</LastModified><ETag>&quot;ecb6d3479ac3823f1da7f314d871989b&quot;</ETag><Size>675</Size><StorageClass>STANDARD</StorageClass><Owner><ID>10680</ID><DisplayName>jpl176</DisplayName></Owner></Contents><Contents><Key>rel_notes.pdf</Key><LastModified>2016-11-09T19:51:38.000Z</LastModified><ETag>&quot;e98cb2ffc748bb65598b7d0af817485f&quot;</ETag><Size>98881</Size><StorageClass>STANDARD</StorageClass><Owner><ID>10680</ID><DisplayName>jpl176</DisplayName></Owner></Contents></ListBucketResult>',
 'headers': {'cache-control': 'no-cache',
             'content-length': '781',
             'content-type': 'application/xml;charset=UTF-8',
             'date': 'Thu, 08 Dec 2016 00:13:00 GMT',
             'expires': 'Thu, 01 Jan 1970 00:00:00 GMT',
             'pragma': 'no-cache',
             'server': 'HGST-HGST Object Storage/3.9.0-6a0e66f36ebe'},
 'reason': 'OK',
 'status': 200}
2016-11-03 03:52       675   s3://176/.profile
2016-11-09 19:51     98881   s3://176/rel_notes.pdf

DEBUG: Bucket 's3://176-encrypt':
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Thu, 08 Dec 2016 00:14:02 +0000\n/176-encrypt/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(176-encrypt): s3p002.hgst-esp.com
DEBUG: ConnMan.get(): re-using connection: https://s3p002.hgst-esp.com#2
DEBUG: format_uri(): /176-encrypt/?delimiter=/
DEBUG: Sending request method_string='GET', uri='/176-encrypt/?delimiter=/', headers={'Authorization': 'AWS jpl176:sJwVJ7wrKrMlNNM7h0IHaB+HZLE=', 'x-amz-date': 'Thu, 08 Dec 2016 00:14:02 +0000'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (https://s3p002.hgst-esp.com#3)
DEBUG: Response:
{'data': '<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>176-encrypt</Name><Prefix></Prefix><Marker/><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>centos6.6-solr4.10.3.qcow2</Key><LastModified>2016-11-29T16:20:06.000Z</LastModified><ETag>&quot;23b82866d8ae477a9582e802468f34c4-160&quot;</ETag><Size>2506096640</Size><StorageClass>STANDARD</StorageClass><Owner><ID>10680</ID><DisplayName>jpl176</DisplayName></Owner></Contents><Contents><Key>foo</Key><LastModified>2016-11-02T22:32:01.000Z</LastModified><ETag>&quot;d1526f516c437c0df7d6895df4674c27&quot;</ETag><Size>185</Size><StorageClass>STANDARD</StorageClass><Owner><ID>10680</ID><DisplayName>jpl176</DisplayName></Owner></Contents><Contents><Key>issue</Key><LastModified>2016-11-29T21:01:56.000Z</LastModified><ETag>&quot;18294170862cc863b3bd71c943fc09a9&quot;</ETag><Size>711</Size><StorageClass>STANDARD</StorageClass><Owner><ID>10680</ID><DisplayName>jpl176</DisplayName></Owner></Contents><Contents><Key>rel_notes.pdf</Key><LastModified>2016-11-09T19:46:27.000Z</LastModified><ETag>&quot;e98cb2ffc748bb65598b7d0af817485f&quot;</ETag><Size>98881</Size><StorageClass>STANDARD</StorageClass><Owner><ID>10680</ID><DisplayName>jpl176</DisplayName></Owner></Contents><CommonPrefixes><Prefix>sanadm01/</Prefix></CommonPrefixes></ListBucketResult>',
 'headers': {'cache-control': 'no-cache',
             'content-length': '1399',
             'content-type': 'application/xml;charset=UTF-8',
             'date': 'Thu, 08 Dec 2016 00:13:00 GMT',
             'expires': 'Thu, 01 Jan 1970 00:00:00 GMT',
             'pragma': 'no-cache',
             'server': 'HGST-HGST Object Storage/3.9.0-6a0e66f36ebe'},
 'reason': 'OK',
 'status': 200}
                       DIR   s3://176-encrypt/sanadm01/
2016-11-29 16:20 2506096640   s3://176-encrypt/centos6.6-solr4.10.3.qcow2
2016-11-02 22:32       185   s3://176-encrypt/foo
2016-11-29 21:01       711   s3://176-encrypt/issue
2016-11-09 19:46     98881   s3://176-encrypt/rel_notes.pdf

DEBUG: Bucket 's3://testbucket':
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Thu, 08 Dec 2016 00:14:03 +0000\n/testbucket/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(testbucket): s3p002.hgst-esp.com
DEBUG: ConnMan.get(): re-using connection: https://s3p002.hgst-esp.com#3
DEBUG: format_uri(): /testbucket/?delimiter=/
DEBUG: Sending request method_string='GET', uri='/testbucket/?delimiter=/', headers={'Authorization': 'AWS jpl176:7KUrFK7LbHxSmytFbwEL8A0Sfvk=', 'x-amz-date': 'Thu, 08 Dec 2016 00:14:03 +0000'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (https://s3p002.hgst-esp.com#4)
DEBUG: Response:
{'data': '<?xml version="1.0" encoding="UTF-8"?><ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>testbucket</Name><Prefix></Prefix><Marker/><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>',
 'headers': {'cache-control': 'no-cache',
             'content-length': '251',
             'content-type': 'application/xml;charset=UTF-8',
             'date': 'Thu, 08 Dec 2016 00:13:00 GMT',
             'expires': 'Thu, 01 Jan 1970 00:00:00 GMT',
             'pragma': 'no-cache',
             'server': 'HGST-HGST Object Storage/3.9.0-6a0e66f36ebe'},
 'reason': 'OK',
 'status': 200}

[jdempsey@centos ~]$

**Comment by fviard** [comment]
Looks like to be resolved now.
