### ISSUE TITLE
S3 error: 403 (InvalidAccessKeyId)

### ISSUE THREAD

**Issue by bfallik** [s3tools/s3cmd#874]
We use STS assumed roles to interact with AWS using elevated permissions. In this scenario we call `aws sts assume-role` to generate temporary credentials and then export thos into the environment for consumption by the AWS CLI. The keys are AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SECURITY_TOKEN, and AWS_SESSION_TOKEN.

This interactions seems to break s3cmd:
```
$ s3cmd ls s3://<BUCKETNAME>/
ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.
```
but works fine using the aws cli:
```
$ aws s3 ls s3://<BUCKETNAME>/
                           PRE artifacts/
                           PRE jenkins/
```

If I inspect s3cmd's debugging output I can see the access key being used:
```
$ echo $AWS_ACCESS_KEY_ID
ASIAJ5Kxxx2UA
$ s3cmd -d ls s3://clypd-engineering/ 2>&1 | grep AWSAccessKeyId
DEBUG: ErrorXML: AWSAccessKeyId: 'ASIAJ5Kxxx2UA'
```

Any idea what's going on here?

**Comment by Palleas** [comment]
From what I understand, `s3cmd` doesn't support this..?

**Comment by fviard** [comment]
Nothing special was done to support sts so far.
See:
https://github.com/s3tools/s3cmd/issues/546

But assuming that you already did an "aws sts assume-role" before, things should be working as if it was normal credentials. My guess is that aws doesn't export the "role credentials" but just the token, or, that we don't take the right thing for this case (ie aws_access_key_id vs secret_acccess_key).

**Comment by M3kH** [comment]
I didn't use **s3cmd** but it just happen that I found this tread that was relate to my issue.
To me what help out is understand that when use `sts::assumeRole` passing `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` is not enough, in fact you also need to pass `AWS_SESSION_TOKEN`.

Hope this helps.

**Comment by TAnas0** [comment]
@M3kH what would the `AWS_SESSION_TOKEN` be? I tried setting it as an access token with read and write permissions, but I am still having the same error.

**Comment by M3kH** [comment]
@TAnas0, not sure relates to your case, in my case I create a session on the fly, based on success on an oAuth success authentication.

This means the `AWS_SESSION_TOKEN` is passed as result from [Assume Role (example)](https://docs.aws.amazon.com/cli/latest/reference/sts/assume-role.html#examples)

And if you got a session created by this setup, you need to pass along also that token.

**Comment by fviard** [comment]
Support for STS assume role and co is now available in master.

See: https://github.com/s3tools/s3cmd/issues/1075#issuecomment-873712964

**Comment by lvsj** [comment]
I've encountered the same error because I have the wrong  **bucket_host**  address

**Comment by janpfeifer** [comment]
!? So the wrong bucket_host yields an `InvalidAccessKeyId` error !?

I wonder what it wants for `bucket_host`, if the default value doesn't work ...
