### ISSUE TITLE
'AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by adarv** [s3tools/s3cmd#922]
I just downloaded the current upstream version from the GitHub and when I try to run it with “python s3cmd –configure’ I got this error

![error](https://user-images.githubusercontent.com/25344705/31086394-64a44240-a7a2-11e7-83f8-d80b2a5122ea.PNG)

any idea what can i do to solve it?

**Comment by fviard** [comment]
@adarv Did you try the last "MASTER" from github? I can be wrong i think it was already fixed some times ago after the release of the 2.0.0

**Comment by adarv** [comment]
yes, I tried the last "MASTER"

**Comment by fviard** [comment]
In fact, are you running on windows?

**Comment by adarv** [comment]
yes

**Comment by fviard** [comment]
Ok, that's why it went unnoticed.
I will have a look at that.

**Comment by fviard** [comment]
@adarv I have pushed a patch in MASTER that should have solved your issue.
Is it possible for you to give it a try to tell me if it works for you?
And if yes, if you are encountering over issues?
(I have not yet really tested the python 3 support on windows)

**Comment by adarv** [comment]
still not working, now i have got another error

![image](https://user-images.githubusercontent.com/25344705/31278092-619fffd2-aaac-11e7-9692-bc14fddfd4a9.png)

**Comment by fviard** [comment]
@adarv the error during report of error should be fixed.
For the main error (OS Error, dlopen...), its look like that you have an issue of setup of the "libmagic" for windows. Libmagic is used to determine file types.

Please have a look at the following page for the installation instructions for windows:
https://github.com/ahupp/python-magic
I think that you have some "dll" to copy.
(it looks like that you have the "python module" but not the real library that the module is using).

Please let me know if you manage to fix that and encounter other issues after.

**Comment by fviard** [comment]
@adarv In fact, I just noticed that there was another issue, s3cmd is supposed to have a fallback in the case that you don't have libmagic or an issue loading it like in your case.
But it looks like that windows was throwing the wrong error for us to detect your case and so use the fallback.

I have pushed a new fix in MASTER that should resolve that. So, if you can try that version, you should be able to continue using s3cmd despite the problem with libmagic.
